version: "3.8"

services:
  sgw:
    container_name: sgw
    restart: always
    image: "airdb/sgw:dev"
    #command: sleep 300
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443/tcp"
      - "80:80/tcp"
      - "8001:8001/tcp"
    volumes:
      - ./conf/:/app/conf
