version: '3.3'

services:
  sgw:
    container_name: sgw
    restart: always
    image: 'airdb/sgw:dev'
    #command: sleep 300
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080/tcp"
      - "8000:8000/tcp"
      - "8001:8001/tcp"
    volumes:
      - ./conf/:/app/conf
